/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteRouteImport } from './routes/console/route'
import { Route as ConsoleAdminRouteImport } from './routes/console/admin'
import { Route as ConsoleFarmerRouteImport } from './routes/console/farmer'
import { Route as ConsoleInvestorRouteImport } from './routes/console/investor'
import { Route as ConsoleMarketRouteImport } from './routes/console/market'
import { Route as ConsoleResearcherRouteImport } from './routes/console/researcher'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleAdminRoute = ConsoleAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleFarmerRoute = ConsoleFarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleInvestorRoute = ConsoleInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleMarketRoute = ConsoleMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleResearcherRoute = ConsoleResearcherRouteImport.update({
  id: '/researcher',
  path: '/researcher',
  getParentRoute: () => ConsoleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/console/admin': typeof ConsoleAdminRoute
  '/console/farmer': typeof ConsoleFarmerRoute
  '/console/investor': typeof ConsoleInvestorRoute
  '/console/market': typeof ConsoleMarketRoute
  '/console/researcher': typeof ConsoleResearcherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/console/admin': typeof ConsoleAdminRoute
  '/console/farmer': typeof ConsoleFarmerRoute
  '/console/investor': typeof ConsoleInvestorRoute
  '/console/market': typeof ConsoleMarketRoute
  '/console/researcher': typeof ConsoleResearcherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/console/admin': typeof ConsoleAdminRoute
  '/console/farmer': typeof ConsoleFarmerRoute
  '/console/investor': typeof ConsoleInvestorRoute
  '/console/market': typeof ConsoleMarketRoute
  '/console/researcher': typeof ConsoleResearcherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/console/admin'
    | '/console/farmer'
    | '/console/investor'
    | '/console/market'
    | '/console/researcher'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/console/admin'
    | '/console/farmer'
    | '/console/investor'
    | '/console/market'
    | '/console/researcher'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/console/admin'
    | '/console/farmer'
    | '/console/investor'
    | '/console/market'
    | '/console/researcher'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/admin': {
      id: '/console/admin'
      path: '/admin'
      fullPath: '/console/admin'
      preLoaderRoute: typeof ConsoleAdminRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/farmer': {
      id: '/console/farmer'
      path: '/farmer'
      fullPath: '/console/farmer'
      preLoaderRoute: typeof ConsoleFarmerRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/investor': {
      id: '/console/investor'
      path: '/investor'
      fullPath: '/console/investor'
      preLoaderRoute: typeof ConsoleInvestorRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/market': {
      id: '/console/market'
      path: '/market'
      fullPath: '/console/market'
      preLoaderRoute: typeof ConsoleMarketRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/researcher': {
      id: '/console/researcher'
      path: '/researcher'
      fullPath: '/console/researcher'
      preLoaderRoute: typeof ConsoleResearcherRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
  }
}

interface ConsoleRouteRouteChildren {
  ConsoleAdminRoute: typeof ConsoleAdminRoute
  ConsoleFarmerRoute: typeof ConsoleFarmerRoute
  ConsoleInvestorRoute: typeof ConsoleInvestorRoute
  ConsoleMarketRoute: typeof ConsoleMarketRoute
  ConsoleResearcherRoute: typeof ConsoleResearcherRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleAdminRoute: ConsoleAdminRoute,
  ConsoleFarmerRoute: ConsoleFarmerRoute,
  ConsoleInvestorRoute: ConsoleInvestorRoute,
  ConsoleMarketRoute: ConsoleMarketRoute,
  ConsoleResearcherRoute: ConsoleResearcherRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
