"""Train the models and export them as inspectable JSON.

Training stays offline in Python.
The generated JSON artifacts are used by the TypeScript application.

For the crash model, the real ATP3 dataset generated by load_atp3.py is used:
    packages/models/data/crash_real.csv
"""

from __future__ import annotations

import json
import pathlib

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


HERE = pathlib.Path(__file__).parent
DATA = HERE.parent / "data"
ARTIFACTS = HERE.parent / "artifacts"
ARTIFACTS.mkdir(exist_ok=True)

SEED = 42


def load(name: str):
    """Read a CSV from packages/models/data."""
    path = DATA / name

    if not path.exists():
        raise SystemExit(
            f"{path} missing — required training dataset was not found"
        )

    raw = np.genfromtxt(
        path,
        delimiter=",",
        names=True,
    )

    if raw.size == 0:
        raise SystemExit(f"{path} is empty")

    cols = list(raw.dtype.names)

    matrix = np.array(
        [raw[c] for c in cols]
    ).T

    return cols, matrix


def fill_missing_values(X: np.ndarray) -> np.ndarray:
    """Replace missing numeric feature values with column medians.

    ATP3 contains a small number of missing temperature observations.
    Median imputation keeps those real pond-days instead of deleting them.
    """

    X = X.copy()

    for column in range(X.shape[1]):

        values = X[:, column]

        valid = values[~np.isnan(values)]

        if len(valid) == 0:
            raise SystemExit(
                f"Feature column {column} contains no valid values."
            )

        median_value = np.median(valid)

        X[np.isnan(values), column] = median_value

    return X


def train_crash() -> None:
    """Culture collapse within 48 h.

    Uses the real ATP3 crash dataset generated by load_atp3.py.

    Logistic regression is intentionally used because the prediction needs
    to remain interpretable for an operator.
    """

    # Real ATP3 data.
    cols, m = load("crash_real.csv")

    X = m[:, :-1]
    y = m[:, -1].astype(int)

    # ATP3 contains 65 missing temperature observations.
    # Replace missing feature values with their column median.
    X = fill_missing_values(X)

    X_tr, X_te, y_tr, y_te = train_test_split(
        X,
        y,
        test_size=0.25,
        random_state=SEED,
        stratify=y,
    )

    scaler = StandardScaler().fit(X_tr)

    # The crash class is a minority class.
    # Balanced weighting prevents the model from simply predicting normal.
    clf = LogisticRegression(
        max_iter=2000,
        class_weight="balanced",
        random_state=SEED,
    ).fit(
        scaler.transform(X_tr),
        y_tr,
    )

    proba = clf.predict_proba(
        scaler.transform(X_te)
    )[:, 1]

    auc = roc_auc_score(
        y_te,
        proba,
    )

    pred = (
        proba >= 0.5
    ).astype(int)

    cm = confusion_matrix(
        y_te,
        pred,
    ).tolist()

    save(
        "crash_classifier",
        {
            "kind": "logistic_regression",
            "features": cols[:-1],
            "mean": scaler.mean_.tolist(),
            "scale": scaler.scale_.tolist(),
            "coef": clf.coef_[0].tolist(),
            "intercept": float(
                clf.intercept_[0]
            ),
            "threshold": 0.5,
        },
        {
            "rows": int(len(y)),
            "positive_rate": float(y.mean()),
            "test_auc": float(auc),
            "confusion_matrix": cm,
            "report": classification_report(
                y_te,
                pred,
                output_dict=True,
                zero_division=0,
            ),
            "note": (
                "Trained on real ATP3 pond data. "
                "The crash label is derived from an observed "
                "optical-density decline within the 48-hour "
                "prediction window. "
                "Missing temperature values were median-imputed. "
                "This model is predictive only and is never used "
                "directly for carbon crediting."
            ),
        },
    )

    print(
        f"  crash_classifier      "
        f"AUC {auc:.3f}   "
        f"({len(y)} rows, {y.mean():.1%} positive)"
    )


def train_divergence() -> None:
    """Noise vs drift vs systematic overstatement across 12 windows."""

    cols, m = load("divergence.csv")

    X = m[:, :-1]
    y = m[:, -1].astype(int)

    X_tr, X_te, y_tr, y_te = train_test_split(
        X,
        y,
        test_size=0.25,
        random_state=SEED,
        stratify=y,
    )

    clf = RandomForestClassifier(
        n_estimators=40,
        max_depth=5,
        min_samples_leaf=8,
        random_state=SEED,
    ).fit(
        X_tr,
        y_tr,
    )

    pred = clf.predict(X_te)

    acc = float(
        (pred == y_te).mean()
    )

    cm = confusion_matrix(
        y_te,
        pred,
    ).tolist()

    trees = []

    for est in clf.estimators_:

        t = est.tree_

        trees.append(
            {
                "feature": t.feature.tolist(),
                "threshold": t.threshold.tolist(),
                "left": t.children_left.tolist(),
                "right": t.children_right.tolist(),
                "value": [
                    v[0].tolist()
                    for v in t.value
                ],
            }
        )

    save(
        "divergence_classifier",
        {
            "kind": "random_forest",
            "features": cols[:-1],
            "classes": [
                "honest",
                "drift",
                "systematic",
            ],
            "trees": trees,
        },
        {
            "rows": int(len(y)),
            "test_accuracy": acc,
            "confusion_matrix": cm,
            "report": classification_report(
                y_te,
                pred,
                output_dict=True,
                zero_division=0,
                target_names=[
                    "honest",
                    "drift",
                    "systematic",
                ],
            ),
            "note": (
                "Sets the watch/flagged verdict only. "
                "It may never influence creditableCo2Kg."
            ),
        },
    )

    print(
        f"  divergence_classifier "
        f"accuracy {acc:.3f}   "
        f"({len(y)} rows, 3 classes)"
    )


def train_ndci() -> None:
    """Chlorophyll index to biomass, with a prediction interval."""

    cols, m = load("ndci.csv")

    X = m[:, :-1]
    y = m[:, -1]

    X_tr, X_te, y_tr, y_te = train_test_split(
        X,
        y,
        test_size=0.25,
        random_state=SEED,
    )

    reg = LinearRegression().fit(
        X_tr,
        y_tr,
    )

    pred = reg.predict(X_te)

    resid = y_te - pred

    r2 = float(
        reg.score(
            X_te,
            y_te,
        )
    )

    safe = pred > 1e-6

    ratios = (
        y_te[safe] /
        pred[safe]
    )

    lo = float(
        np.quantile(
            ratios,
            0.1,
        )
    )

    hi = float(
        np.quantile(
            ratios,
            0.9,
        )
    )

    save(
        "ndci_biomass",
        {
            "kind": "linear_regression",
            "features": cols[:-1],
            "coef": reg.coef_.tolist(),
            "intercept": float(
                reg.intercept_
            ),
            "interval_low_ratio": lo,
            "interval_high_ratio": hi,
        },
        {
            "rows": int(len(y)),
            "test_r2": r2,
            "residual_std": float(
                resid.std()
            ),
            "implied_error_factor": float(
                hi / max(lo, 1e-9)
            ) ** 0.5,
            "note": (
                "The interval matters more than the fit. "
                "A wide interval simply means we credit less."
            ),
        },
    )

    print(
        f"  ndci_biomass          "
        f"R2 {r2:.3f}, "
        f"interval x{lo:.2f}–x{hi:.2f}   "
        f"({len(y)} rows)"
    )


def save(
    name: str,
    model: dict,
    meta: dict,
) -> None:

    (
        ARTIFACTS /
        f"{name}.json"
    ).write_text(
        json.dumps(
            model,
            indent=2,
        )
        + "\n"
    )

    (
        ARTIFACTS /
        f"{name}.meta.json"
    ).write_text(
        json.dumps(
            meta,
            indent=2,
        )
        + "\n"
    )


if __name__ == "__main__":

    print("training…")

    train_crash()
    train_divergence()
    train_ndci()

    print(
        "\nartifacts written to "
        "packages/models/artifacts/"
    )