'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useApiData } from '@/lib/use-api-data';
import type { PinSignal } from '@/lib/use-live-stream';
import { ResourceState } from './detail-sheet';
import { RelatedLinks } from './related-links';
import { rupees } from './market-insights';
interface Part {ref:string;part:string;role:string;bus:string;pin:string|null;qty:number;unitInr:number;supplyV:number|null;drawMa:number;duty:number}
interface Circuit {kit:string;channels:string[];parts:Part[];nets:{from:string;to:string;label:string}[];bomInr:number;power:{avgMaAt12V:number;dailyWh:number;panelW:number;batteryAh:number;autonomyDays:number};notes:string[]}
interface NodePlan {sizing:{nodes:number;because:string}|null;circuit:Circuit;totalInr:number}
interface SiteCircuit {site:{id:string;name:string;tier:string};ponds:{pondId:string;label:string;areaM2:number;kit:string;nodes:number;because:string;nodeInr:number;totalInr:number}[];totals:{nodes:number;gatewayInr:number;hardwareInr:number}}
interface SensorPlan {items:{name:string;qty:number;unitInr:number;totalInr:number;because:string}[];totals:{nodes:number;capexInr:number};cadence:{publishSeconds:number;because:string};notes:string[];ponds:{pondId:string;label:string;placement:string;because:string;depthOfProbeM:number|null;instrument:boolean}[]}
export function HardwareWorkspace() {
 const [site,setSite]=useState(''),[area,setArea]=useState(1200),[count,setCount]=useState(1),[tier,setTier]=useState('small'),[pond,setPond]=useState('');
 useEffect(()=>{setSite(new URLSearchParams(location.search).get('site')??'');},[]);
 const sites=useApiData<{id:string;name:string}[]>('/fleet');
 const siteCircuit=useApiData<SiteCircuit>(site?`/land/site/${encodeURIComponent(site)}/circuit`:null);
 const plan=useApiData<SensorPlan>(site?`/land/site/${encodeURIComponent(site)}/sensor-plan`:null);
 const chosen=siteCircuit.data?.ponds.find(p=>p.pondId===pond)??siteCircuit.data?.ponds[0];
 const valid=area>0&&Number.isFinite(area)&&count>=1&&Number.isInteger(count);
 const query=site?(chosen?`kit=${chosen.kit}&areaM2=${chosen.areaM2}`:null):valid?`areaM2=${area}&tier=${tier}`:null;
 const node=useApiData<NodePlan>(query?`/land/hardware/circuit?${query}`:null);
 const c=node.data?.circuit;
 return <>
 <section className="panel market-form"><h2>Size your simulated sensor network</h2><p>Choose a farm, or describe equal-sized ponds. All prices are Indian retail estimates; no physical hardware is being purchased.</p><label>Farm<select value={site} onChange={e=>{setSite(e.target.value);setPond('');}}><option value="">Enter pond dimensions</option>{sites.data?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{sites.error&&<p className="helper">Farm catalogue: {sites.error} You can still enter dimensions.</p>}
 {!site?<div className="market-filters"><label>Area per pond (m²)<input type="number" min="1" value={area} onChange={e=>setArea(Number(e.target.value))}/></label><label>Pond count<input type="number" min="1" step="1" value={count} onChange={e=>setCount(Number(e.target.value))}/></label><label>Evidence tier<select value={tier} onChange={e=>setTier(e.target.value)}>{['smallholder','small','mid','facility'].map(t=><option key={t}>{t}</option>)}</select></label></div>:<><RelatedLinks siteId={site}/><ResourceState {...siteCircuit} empty={siteCircuit.data?.ponds.length===0}/>{siteCircuit.data&&<><div className="summary-grid"><div className="summary-card"><span>Nodes needed</span><strong className="num">{siteCircuit.data.totals.nodes}</strong></div><div className="summary-card"><span>Hardware including gateway</span><strong className="num">{rupees(siteCircuit.data.totals.hardwareInr)}</strong></div><div className="summary-card"><span>Gateway</span><strong className="num">{rupees(siteCircuit.data.totals.gatewayInr)}</strong></div></div><label>Inspect a pond’s circuit<select value={chosen?.pondId??''} onChange={e=>setPond(e.target.value)}>{siteCircuit.data.ponds.map(p=><option value={p.pondId} key={p.pondId}>{p.label} · {p.kit} · {p.nodes} nodes</option>)}</select></label>{siteCircuit.data.ponds.map(p=><article key={p.pondId} className="market-record"><Link href={`/console/pond/${p.pondId}`}>{p.label}</Link> · {p.nodes} × {rupees(p.nodeInr)} = {rupees(p.totalInr)}<p>{p.because}</p></article>)}</>}</>}
 <ResourceState {...node}/>{!site&&node.data&&<div className="summary-grid"><div className="summary-card"><span>Nodes needed</span><strong className="num">{(node.data.sizing?.nodes??1)*count}</strong><p>{node.data.sizing?.because}</p></div><div className="summary-card"><span>Estimated node hardware</span><strong className="num">{rupees(node.data.totalInr*count)}</strong><p>Node parts only. Site gateways and farm construction are separate.</p></div></div>}
 </section>
 {c&&<><section className="panel"><p className="eyebrow">{c.kit.toUpperCase()} NODE</p><h2>From pond conditions to digital readings</h2><div className="hw-channels">{c.channels.map(channel=><article key={channel}><h3>{channel}</h3><p>{c.parts.find(p=>p.role===channel)?.part}</p></article>)}</div>{c.notes.map(n=><p className="helper" key={n}>{n}</p>)}</section><section className="panel"><h2>Simulated wiring</h2><p>Connections and pin names come from the circuit model. Each row is one signal or power connection.</p><CircuitDiagram circuit={c}/><details><summary>Connection list</summary>{c.nets.map((n,i)=><p key={i}>{n.from} → {n.to} · {n.label}</p>)}</details></section><section className="panel"><h2>Every component, priced</h2><p>One {c.kit} node: {rupees(c.bomInr)}. Component costs are estimates, not expenses already paid.</p><div className="hardware-parts">{c.parts.map(p=><article className="market-record" key={p.ref}><h3>{p.ref} · {p.part}</h3><p>{p.role} · {p.bus}{p.pin?` · ${p.pin}`:''}</p><p>{p.qty} × {rupees(p.unitInr)} = <strong>{rupees(p.qty*p.unitInr)}</strong></p><small>{p.supplyV===null?'Passive component':`${p.supplyV} V · ${p.drawMa} mA · ${(p.duty*100).toFixed(0)}% duty`}</small></article>)}</div></section><section className="panel"><h2>Power budget</h2><dl className="kv"><dt>Daily energy</dt><dd>{c.power.dailyWh.toFixed(1)} Wh</dd><dt>Average draw at 12 V</dt><dd>{c.power.avgMaAt12V.toFixed(1)} mA</dd><dt>Solar panel</dt><dd>{c.power.panelW} W</dd><dt>Battery</dt><dd>{c.power.batteryAh} Ah</dd><dt>Modelled autonomy</dt><dd>{c.power.autonomyDays.toFixed(1)} days</dd></dl></section><SignalExplorer channels={c.channels} pins={c.parts.flatMap(p=>p.pin?[p.pin]:[])}/></>}
 {site&&<section className="panel"><h2>Probe placement and commercial sonde comparison</h2><ResourceState {...plan}/>{plan.data&&<><p>The commercial sensor plan is a separate design from the discrete circuit above. Its costs are not added to the circuit bill.</p><p>{plan.data.totals.nodes} instruments · {rupees(plan.data.totals.capexInr)}</p><p>Publish every {plan.data.cadence.publishSeconds} seconds · {plan.data.cadence.because}</p>{plan.data.ponds.map(p=><article className="market-record" key={p.pondId}><h3>{p.label}</h3><p>{p.placement}</p><p>{p.because}</p>{p.depthOfProbeM!==null&&<p>Probe depth: {p.depthOfProbeM} m</p>}</article>)}<details><summary>Commercial plan cost breakdown</summary>{plan.data.items.map((p,i)=><p key={i}>{p.name}: {p.qty} × {rupees(p.unitInr)} = {rupees(p.totalInr)} · {p.because}</p>)}</details>{plan.data.notes.map(n=><p key={n}>{n}</p>)}</>}</section>}
 </>;
}
function CircuitDiagram({circuit:c}:{circuit:Circuit}) {
 const height=c.nets.length*78+12;
 return <div className="circuit-scroll" tabIndex={0} role="region" aria-label="Wiring diagram, scroll horizontally to inspect"><svg viewBox={`0 0 760 ${height}`} className="circuit-diagram" role="img" aria-label={`${c.kit} sensor circuit wiring`}>
 {c.nets.map((n,i)=>{const from=c.parts.find(p=>p.ref===n.from.split('.')[0]),to=c.parts.find(p=>p.ref===n.to.split('.')[0]);const y=i*78+8;return <g key={`${n.from}-${n.to}`}><rect x="4" y={y} width="240" height="60" rx="10" fill="#edf5eb" stroke="#9fb69e"/><rect x="516" y={y} width="240" height="60" rx="10" fill="#133e2e"/><path d={`M244 ${y+30}H508m-7 -5 7 5-7 5`} fill="none" stroke="#448455" strokeWidth="2"/><text x="16" y={y+24} fontSize="14" fill="#173b29">{n.from}</text><text x="16" y={y+45} fontSize="11" fill="#173b29">{from?.role.slice(0,32)??n.from}</text><text x="530" y={y+24} fontSize="14" fill="#eff9ed">{n.to}</text><text x="530" y={y+45} fontSize="11" fill="#eff9ed">{to?.part.slice(0,32)??n.to}</text><text x="380" y={y+17} textAnchor="middle" fontSize="11" fill="currentColor">{n.label.slice(0,35)}</text></g>})}</svg></div>;
}
function SignalExplorer({channels,pins}:{channels:string[];pins:string[]}) {
 const [r,setR]=useState({tempC:28,ph:8,doMgL:7,od:.4,paddlewheelOn:true});
 const result=useApiData<PinSignal[]>(`/land/hardware/signals?${new URLSearchParams(Object.entries(r).map(([k,v])=>[k,String(v)]))}`);
 return <section className="panel"><h2>Try the simulated signals</h2><p>Illustrative inputs show how readings become voltages and digital counts. The selected kit measures {channels.join(', ')}.</p><div className="market-filters">{([['tempC','Water temperature (°C)'],['ph','pH'],['doMgL','Oxygen (mg/L)'],['od','Optical density']] as const).map(([key,label])=><label key={key}>{label}<input type="number" step="any" value={r[key]} onChange={e=>setR({...r,[key]:Number(e.target.value)})}/></label>)}<label>Mixer<select value={String(r.paddlewheelOn)} onChange={e=>setR({...r,paddlewheelOn:e.target.value==='true'})}><option value="true">Running</option><option value="false">Stopped</option></select></label></div><ResourceState {...result}/>{result.data?.filter(s=>pins.includes(s.pin)).map(s=><p key={s.pin}><strong>{s.pin} · {s.channel}</strong>: {s.volts===null?'digital':`${s.volts} V`} · raw {s.raw}{s.saturated?' · Saturated: outside supported range':''}</p>)}</section>;
}
