'use client';
import Link from 'next/link';
import { useState } from 'react';
import { PondView } from './pond-view';
import './simulation-workspace.css';
import { useLiveStream } from '@/lib/use-live-stream';
export function LiveDashboard({pondId,siteId,areaM2,depthM}:{pondId?:string;siteId?:string;areaM2?:number;depthM?:number}) {
 const [selected,setSelected]=useState('ph');
 const [sensors,setSensors]=useState([{id:'ph',label:'pH',x:.29,y:.24},{id:'do',label:'O₂',x:.46,y:.76},{id:'od',label:'Density',x:.73,y:.24},{id:'temp',label:'Temp',x:.8,y:.76}]);
 const live=useLiveStream({pondId,siteId});
 const t=live.readings.find(r=>r.pondId===pondId);
 const r=t?.readings;
 const pins:Record<string,string>={GPIO34:'ph',GPIO35:'do',GPIO32:'od',GPIO4:'temp'};
 const latest=Math.max(...live.sources.map(s=>Date.parse(s.lastAt)).filter(Number.isFinite));
 const age=Number.isFinite(latest)?Math.max(0,Math.floor((live.now-latest)/1000)):null;
 return <section className="panel live-dashboard" aria-label="Live pond readings"><div className="section-heading"><h2>Live readings</h2><span className={`live-indicator ${live.connection}`}><span aria-hidden="true">●</span> {live.connection==='live'?'Stream connected':live.connection==='polling'?'Polling every 5 s':live.connection==='paused'?'Paused while hidden':live.connection==='offline'?'Connection unavailable':'Connecting…'}</span></div><p className="helper">{age===null?'Waiting for a recorded reading.':`Last reading ${age} seconds ago.`} A connected stream does not mean the readings are fresh.</p>{live.error&&<p role="status">{live.error}</p>}{r&&areaM2&&depthM&&r.tempC!==null&&r.ph!==null&&r.doMgL!==null&&r.od!==null&&r.paddlewheelOn!==null&&<div className="live-pond-scene"><PondView daily={[{temperatureC:r.tempC,ph:r.ph,dissolvedOxygenMgL:r.doMgL,opticalDensity:r.od}]} areaM2={areaM2} depthM={depthM} mixing={r.paddlewheelOn} sensors={sensors} day={0} airTemperature={r.tempC} selectedSensor={selected} onSelectSensor={setSelected} onMoveSensor={(id,x,y)=>setSensors(old=>old.map(s=>s.id===id?{...s,x,y}:s))} pinValues={Object.fromEntries((t?.signals??[]).filter(s=>pins[s.pin]).map(s=>[pins[s.pin]!,`${s.volts===null?'digital':`${s.volts} V`} · ${s.raw}`]))}/><p className="helper">Live pond readings; geometry is an illustrative 3:1 footprint. Pin voltages are simulated by the backend.</p></div>}<div className="live-reading-grid">{live.readings.map(t=><article key={t.pondId}><Link href={`/console/pond/${t.pondId}`}>{pondId?'This pond':`Pond ${t.pondId.slice(0,8)}`}</Link><span className="helper"> · {t.source==='sim'?'Simulator':t.source==='device'?'Device':'Source not recorded'}</span><dl>{[['Temperature',t.readings.tempC,'°C'],['pH',t.readings.ph,''],['Oxygen',t.readings.doMgL,'mg/L'],['Density',t.readings.od,'OD']].map(([label,value,unit])=><div key={String(label)}><dt>{label}</dt><dd><span className="reading-change" key={`${label}-${value}`}>{value==null?'—':`${Number(value).toFixed(2)} ${unit}`}</span></dd></div>)}</dl><p>Mixer: {t.readings.paddlewheelOn===null?'not reported':t.readings.paddlewheelOn?'running':'stopped'}</p>{t.signals&&<details><summary>Simulated circuit pin readings</summary>{t.signals.map(s=><p key={`${s.pin}-${s.channel}`}>{s.pin} · {s.channel}: {s.volts===null?'digital':`${s.volts.toFixed(3)} V`} · raw {s.raw}{s.saturated?' · saturated':''}</p>)}</details>}</article>)}</div><details open={live.alerts.length>0}><summary>Incoming alerts ({live.alerts.length})</summary><div aria-live="polite">{live.alerts.length?live.alerts.map(a=><article className="market-record" key={a.id}><strong>{live.now-a.arrivedAt<30000?'New · ':''}{a.severity}</strong><p>{a.message}</p><Link href={`/console/pond/${a.pondId}`}>Inspect pond →</Link><small> · {new Date(a.detectedAt).toLocaleString()}</small></article>):<p>No alerts have arrived in this session.</p>}</div></details></section>;
}
