'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useRole } from '@/lib/session';
import { siteAllowed } from '@/lib/auth-contract';
import { apiData, useApiData } from '@/lib/use-api-data';
import { ResourceState } from './detail-sheet';
import { rupees } from './market-insights';
interface Harvest {harvestId:string;pondLabel:string;harvestedAt:string;dryMassKg:number;listedKg:number|null;soldKg:number;worthInr:number;gradeLabel:string;compositionSource:string|null}
interface Preview {siteName:string;checkCount:number;reportHash:string;blockers:string[];report:{totals:{claimedCo2Kg:number;creditableCo2Kg:number};checks:{id:string;pondLabel:string;creditableCo2Kg:number}[]}}
export function MarketListingForm({onChanged}:{onChanged:()=>void}) {
 const {session}=useRole();const sites=useApiData<{id:string;name:string}[]>('/fleet');const [site,setSite]=useState(session?.account.siteId??'');
 const [kind,setKind]=useState<'credit'|'produce'>('produce');
 return <section className="panel market-form"><h2>Create a listing</h2><p>Choose your farm, review its records, then confirm what to list.</p><ResourceState {...sites}/><label>Farm<select value={site} onChange={e=>setSite(e.target.value)}><option value="">Choose a farm</option>{sites.data?.filter(s=>session&&siteAllowed(session,s.id)).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Listing type<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="produce">Harvested algae</option><option value="credit">Issue a carbon batch</option></select></label>{site&&(kind==='produce'?<HarvestListing key={site} siteId={site} onChanged={onChanged}/>:<BatchListing key={site} siteId={site} onChanged={onChanged}/>)}</section>;
}
function HarvestListing({siteId,onChanged}:{siteId:string;onChanged:()=>void}) {
 const [revision,setRevision]=useState(0);const r=useApiData<Harvest[]>(`/market/produce/site/${siteId}`,revision);
 const [id,setId]=useState(''),[kg,setKg]=useState(0),[price,setPrice]=useState(0),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const harvest=r.data?.find(h=>h.harvestId===id);const valid=!!harvest&&kg>0&&kg<=harvest.dryMassKg-harvest.soldKg&&Number.isFinite(kg)&&price>0&&Number.isFinite(price);
 async function submit(){if(busy||!valid)return;setBusy(true);setMessage('');try{await apiData(`/market/produce/${id}/list`,{method:'POST',body:JSON.stringify({kg,askingInrPerKg:price})});setMessage('Harvest listed.');setReview(false);setId('');setRevision(n=>n+1);onChanged();}catch(e){setMessage(e instanceof Error?e.message:'Could not list.');}finally{setBusy(false);}}
 return <><ResourceState {...r} empty={r.data?.filter(h=>h.listedKg===null).length===0}/>{review&&harvest?<><h3>Review harvest listing</h3><p>{harvest.pondLabel} · {harvest.gradeLabel}</p><p>{kg} kg at {rupees(price)}/kg · asking value {rupees(kg*price)}</p><p>Composition: {harvest.compositionSource??'Not recorded'}. Asking value is not earned revenue.</p><button className="button secondary" disabled={busy} onClick={()=>setReview(false)}>Edit details</button><button className="button" disabled={busy} onClick={submit}>{busy?'Listing…':'Confirm listing'}</button></>:<><label>Unlisted harvest<select value={id} onChange={e=>{const h=r.data?.find(h=>h.harvestId===e.target.value);setId(e.target.value);setKg(h?h.dryMassKg-h.soldKg:0);setPrice(h&&h.dryMassKg>0?Math.round(h.worthInr/h.dryMassKg):0);}}><option value="">Choose a harvest</option>{r.data?.filter(h=>h.listedKg===null).map(h=><option key={h.harvestId} value={h.harvestId}>{h.pondLabel} · {h.harvestedAt.slice(0,10)} · {h.dryMassKg-h.soldKg} kg</option>)}</select></label>{harvest&&<><p>Suggested quantity uses unsold dry mass. Suggested price uses the API’s grade valuation.</p><label>Quantity (kg)<input type="number" min="0.01" step="any" max={harvest.dryMassKg-harvest.soldKg} value={kg} onChange={e=>setKg(Number(e.target.value))}/></label><label>Asking price (₹/kg)<input type="number" min="0.01" step="any" value={price} onChange={e=>setPrice(Number(e.target.value))}/></label><button className="button" disabled={!valid} onClick={()=>setReview(true)}>Review listing →</button></>}</>}{message&&<p role="status">{message}</p>}</>;
}
function BatchListing({siteId,onChanged}:{siteId:string;onChanged:()=>void}) {
 const [start,setStart]=useState(''),[end,setEnd]=useState(''),[disposition,setDisposition]=useState('biochar'),[ref,setRef]=useState('');
 const [preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState<{id:string;creditableCo2Kg:number;note:string}|null>(null);
 const body=()=>({siteId,periodStart:new Date(start).toISOString(),periodEnd:new Date(end).toISOString(),disposition,dispositionEvidenceRef:ref.trim()});
 async function submit(issue:boolean){if(busy)return;setBusy(true);setError('');try{if(issue){setDone(await apiData('/batches',{method:'POST',body:JSON.stringify(body())}));setPreview(null);onChanged();}else setPreview(await apiData('/batches/preview',{method:'POST',body:JSON.stringify(body())}));}catch(e){setError(e instanceof Error?e.message:'Could not complete request.');}finally{setBusy(false);}}
 if(done)return <div><h3>Batch issued and listed</h3><p>{done.creditableCo2Kg} kg · {done.note}</p><Link className="button" href={`/verify/batch/${done.id}`}>Inspect batch →</Link><p>Set a custom asking price from My activity by pausing and relisting this batch.</p></div>;
 return <>{preview?<><h3>Review issuance · {preview.siteName}</h3><p>{preview.checkCount} checks · {preview.report.totals.claimedCo2Kg} kg claimed · <strong>{preview.report.totals.creditableCo2Kg} kg eligible</strong></p><p>{start} to {end} · {disposition} · Evidence: {ref}</p><p className="reference">Report hash: {preview.reportHash}</p>{preview.report.checks.map(c=><p key={c.id}><Link href={`/verify/${c.id}`}>{c.pondLabel}: {c.creditableCo2Kg} kg</Link></p>)}{preview.blockers.map(b=><p role="alert" key={b}>{b}</p>)}<button className="button secondary" disabled={busy} onClick={()=>setPreview(null)}>Edit details</button><button className="button" disabled={busy||preview.blockers.length>0} onClick={()=>submit(true)}>{busy?'Issuing…':'Confirm and issue batch'}</button></>:<form className="market-form" onSubmit={e=>{e.preventDefault();void submit(false);}}><label>Period start (local time)<input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Period end (local time)<input required type="datetime-local" value={end} min={start} onChange={e=>setEnd(e.target.value)}/></label><label>Durable use<select value={disposition} onChange={e=>setDisposition(e.target.value)}>{['biochar','buried','bioplastic'].map(d=><option key={d}>{d}</option>)}</select></label><label>Disposition evidence reference<input required value={ref} onChange={e=>setRef(e.target.value)}/></label><p>Feed and fertiliser cannot be issued as carbon removal. The preview checks eligibility before anything is issued.</p><button className="button" disabled={busy||!start||!end||end<=start||!ref.trim()}>{busy?'Checking…':'Preview eligible credits →'}</button></form>}{error&&<p role="alert" className="err">{error}</p>}</>;
}
