/**
 * Orchestration for a reconciliation run.
 *
 * Gathers the three inputs the engine needs — the claim, the independent
 * evidence, the physics bound — hands them over, and records the result.
 *
 * Note what this service does NOT do: it never computes a fallback figure from
 * the operator's own telemetry when independent evidence is missing. If there
 * is nothing to check against, the engine returns `insufficient_evidence` and
 * credits zero. Refusing is the safe failure.
 */

import {
  consecutiveSameDirection,
  getObservations,
  getPond,
  insertDivergenceCheck,
  meanTemperatureC,
  sumClaimedCo2Kg,
} from '../db/client.ts';
import { reconcile, type ReconcileResult } from '../reconcile/engine.ts';

// The WASM physics module. This is the ONLY physics import allowed in the API:
// pond geometry and a date in, arithmetic out. No simulator, no ground truth.
// @ts-expect-error — generated by `npm run physics:build`, no types shipped
import { physics_ceiling_co2_kg } from '../../../../packages/physics/pkg/index.js';

/** Day of year, 1–365, in UTC. */
function dayOfYear(d: Date): number {
  const start = Date.UTC(d.getUTCFullYear(), 0, 0);
  return Math.floor((d.getTime() - start) / 86_400_000);
}

function windowDays(start: Date, end: Date): number {
  const days = Math.ceil((end.getTime() - start.getTime()) / 86_400_000);
  return Math.max(1, days);
}

/**
 * Temperature fallback when telemetry gave us none.
 *
 * Chosen to be favourable to the operator: 30 °C is near optimal for spirulina,
 * so it produces a HIGHER ceiling than a colder assumption would. Erring
 * generous keeps the bound a bound — we would rather miss a marginal claim than
 * reject an honest one on a guess.
 */
const ASSUMED_TEMP_C = 30;

export interface ReconciliationRecord extends ReconcileResult {
  checkId: string;
  pondId: string;
  windowStart: string;
  windowEnd: string;
}

export async function runReconciliation(
  pondId: string,
  windowStart: Date,
  windowEnd: Date,
): Promise<ReconciliationRecord | null> {
  const pond = await getPond(pondId);
  if (!pond) return null;

  const startIso = windowStart.toISOString();
  const endIso = windowEnd.toISOString();

  const [claimedCo2Kg, observations, measuredTemp] = await Promise.all([
    sumClaimedCo2Kg(pondId, startIso, endIso),
    getObservations(pondId, startIso, endIso),
    meanTemperatureC(pondId, startIso, endIso),
  ]);

  const meanTempC = measuredTemp ?? ASSUMED_TEMP_C;

  const ceilingCo2Kg: number = physics_ceiling_co2_kg(
    pond.latDeg,
    pond.areaM2,
    pond.depthM,
    dayOfYear(windowStart),
    windowDays(windowStart, windowEnd),
    meanTempC,
  );

  // Direction of the prior run, so a sustained overstatement is visible even
  // when each individual window looks unremarkable.
  const priorRun = await consecutiveSameDirection(pondId, 1);

  const result = reconcile({
    pond,
    windowStart,
    windowEnd,
    claimedCo2Kg,
    observations,
    meanTempC: measuredTemp,
    priorRun,
    ceilingCo2Kg,
  });

  const checkId = await insertDivergenceCheck({
    pondId,
    windowStart: startIso,
    windowEnd: endIso,
    claimedCo2Kg: result.claimedCo2Kg,
    independentCo2Kg: result.independentCo2Kg,
    independentLowCo2Kg: result.independentLowCo2Kg,
    independentHighCo2Kg: result.independentHighCo2Kg,
    ceilingCo2Kg: result.ceilingCo2Kg,
    divergence: result.divergence,
    consecutiveSameDirection: result.consecutiveSameDirection,
    verdict: result.verdict,
    creditableCo2Kg: result.creditableCo2Kg,
    reason: result.reason,
  });

  return { ...result, checkId, pondId, windowStart: startIso, windowEnd: endIso };
}
