/**
 * Ambient declaration for the wasm-pack output.
 *
 * WHY THIS EXISTS AND WHY IT IS DANGEROUS
 *
 * `packages/physics/pkg/` is generated by wasm-pack and deliberately not
 * committed, so on a clean checkout (CI, a new laptop) TypeScript has nothing
 * to resolve `rtz_physics.js` against. This declaration fills that gap.
 *
 * It is therefore a HAND-MAINTAINED COPY OF GENERATED TYPES, which drifts
 * silently: it broke CI once already, when `inject_pump_failure` and
 * `with_conditions` were added to the Rust and never added here. Locally
 * everything passed because the real generated pkg was present.
 *
 * If you add a #[wasm_bindgen] method, add it here in the same commit.
 * CI now runs `npm run physics:build` before typecheck, so a mismatch
 * between this file and the real bindings will surface there.
 */
declare module '*rtz_physics.js' {
  export function physics_ceiling_co2_kg(
    lat: number, area: number, depth: number, day: number, days: number, temp: number,
  ): number;
  export function version(): string;
  export function co2_from_biomass(kg: number): number;

  export interface Reading {
    ph: number;
    dissolved_oxygen_mg_l: number;
    temperature_c: number;
    optical_density: number;
    reported_co2_kg: number;
    /** Protein mass fraction of dry biomass, 0..1. */
    protein_frac: number;
    /** Lipid fraction. Climbs under nitrogen stress — the value lever. */
    lipid_frac: number;
    carbohydrate_frac: number;
    /** Sun's angle above the horizon, degrees. Negative means night. */
    solar_elevation_deg: number;
    /** PAR reaching the water now, µmol/m²/s. Zero at night. */
    par_umol: number;
    /** Hours between sunrise and sunset today. */
    daylight_hours: number;
    /** Paddlewheel draw this hour, kWh. Zero while the mixer is stopped. */
    energy_kwh: number;
    hour: number;
    day_of_year: number;
    free(): void;
  }

  export class WasmPond {
    constructor(lat: number, area: number, depth: number, seed: bigint, day: number);
    /** Site conditions spelled out, rather than the Gujarat defaults. */
    static with_conditions(
      lat: number, area: number, depth: number, seed: bigint, day: number,
      meanAirTempC: number, diurnalSwingC: number, influentNitrogenMgL: number,
    ): WasmPond;
    step(): Reading;
    harvest(fraction: number): number;
    inject_overstatement(factor: number, start: number, duration: number): void;
    inject_crash(severity: number, start: number, duration: number): void;
    /** Paddlewheel stops: the pond stratifies and the energy meter reads 0. */
    inject_pump_failure(start: number, duration: number): void;
    standing_biomass_kg(): number;
    ground_truth_co2_kg_offline_scoring_only(): number;
    free(): void;
  }
}
