import Link from 'next/link';
import { EmptyState } from '@/components/ui';
import { RefreshControls } from '@/components/refresh-controls';
import { money, mass } from '@/lib/display';
export const dynamic = 'force-dynamic';
interface Economics { breakdown: { category: string; totalInr: number; energyKwh: number | null }[]; totalCostInr: number; creditedCo2Kg: number; costPerTonneCo2Inr: number | null; }
const LABELS: Record<string, string> = { paddlewheel: 'Keeping the water moving', pumping: 'Water pumps', harvesting: 'Collecting the algae', drying: 'Drying the algae', nutrients: 'Plant nutrients', co2: 'Carbon dioxide supply', make_up_water: 'Replacement water', labour: 'Staff and labour', maintenance: 'Repairs and maintenance', platform: 'Monitoring service' };
export default async function SitePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  let e: Economics | null = null;
  try { const r = await fetch(`${process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000'}/fleet/site/${encodeURIComponent(id)}/economics`, { cache: 'no-store', signal: AbortSignal.timeout(8000) }); if (r.ok) e = await r.json(); } catch { /* Render a recoverable connection state below. */ }
  return <main className="wrap"><Link className="back" href="/console">← Back to my ponds</Link><div className="page-heading"><div><p className="eyebrow">FARM COSTS</p><h1>Know where the money goes.</h1><p>A simple breakdown of the costs recorded for this farm.</p></div><RefreshControls /></div>
    {!e ? <EmptyState title="We couldn’t load these costs"><p>The connection may be unavailable. Refresh to try again.</p></EmptyState> : !e.breakdown.length ? <EmptyState title="No expenses recorded yet"><p>Once farm expenses are added, you’ll see the total and a breakdown here. Missing expenses do not mean the farm costs nothing to run.</p><Link className="button secondary" href="/sim">Explore sample running costs →</Link></EmptyState> : <>
      <div className="summary-grid"><div className="summary-card"><span>Total recorded costs</span><strong className="num" style={{ fontSize: 'clamp(1.5rem, 3vw, 2.2rem)' }}>{money(e.totalCostInr)}</strong><small>All expense records currently available</small></div><div className="summary-card"><span>Harvesting and drying</span><strong className="num" style={{ fontSize: 'clamp(1.5rem, 3vw, 2.2rem)' }}>{money(e.breakdown.filter((b) => ['harvesting', 'drying'].includes(b.category)).reduce((n, b) => n + b.totalInr, 0))}</strong><small>Collecting algae and removing water</small></div><div className="summary-card"><span>Recorded electricity use</span><strong className="num" style={{ fontSize: 'clamp(1.5rem, 3vw, 2.2rem)' }}>{e.breakdown.some((b) => b.energyKwh !== null) ? `${e.breakdown.reduce((n, b) => n + (b.energyKwh ?? 0), 0).toLocaleString('en-IN')} kWh` : 'Not recorded'}</strong><small>kWh is the unit used on an electricity bill</small></div></div>
      <section className="panel"><h2>Cost breakdown</h2><p className="sub">Longer bars mean a larger share of the recorded costs.</p>{e.breakdown.map((b) => <div className="cost-row" key={b.category}><div className="cost-head"><span>{LABELS[b.category] ?? b.category.replaceAll('_', ' ')}</span><strong className="num">{money(b.totalInr)}</strong></div><div className="bar" aria-hidden="true"><div className="bar-fill" style={{ width: `${e.totalCostInr > 0 ? Math.min(100, b.totalInr / e.totalCostInr * 100) : 0}%` }} /></div></div>)}<details className="technical"><summary>Carbon credit figures</summary><dl className="kv"><dt>Issued credits recorded</dt><dd>{mass(e.creditedCo2Kg)}</dd><dt>Cost per tonne of issued credits</dt><dd>{e.costPerTonneCo2Inr === null ? 'Not available yet' : money(e.costPerTonneCo2Inr)}</dd></dl><p className="helper">One tonne is 1,000 kg. This uses recorded issuance, which is separate from a pond’s estimated carbon absorption.</p></details></section>
    </>}
  </main>;
}
